#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: CS373 Spring 2016 Jena Cameron

# Short bio or description (displayed in the header)
description: Follow me on the road to success 
		<select name="My favorite things">
		    <option value="Raindrops on roses">Raindrops on roses</option>
		    <option value="Whiskers on kittens">Whiskers on kittens</option>
		</select>
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://41.media.tumblr.com/5d339c8ea407d1509113b0f599b00547/tumblr_o27ru6QeRK1r3er6io1_400.png
 
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: jlciam@utexas.edu
  facebook:
  flickr:
  github: jlciam
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jlciam
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +JenaCameron # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-72765677-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://wickedkitten.me

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji # Use emojis 

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
